routing_admin:
        resource: "@BlackhouseappBluehouseappBundle/Resources/config/routing/backend/admin/routing_admin.yml"
routing_manager:
        resource: "@BlackhouseappBluehouseappBundle/Resources/config/routing/backend/manager/routing_manager.yml"
routing_frontEnd:
        resource: "@BlackhouseappBluehouseappBundle/Resources/config/routing/frontend/routing_frontEnd.yml"




_imagine:
    resource: .
    type:     imagine

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile