bluehouseapp_audit_index:
    path:     /
    defaults: { _controller: "bluehouseapp.controller.audit:indexAction" }

bluehouseapp_audit_post_delete:
    path:     /post_delete
    defaults: { _controller: "bluehouseapp.controller.audit:deletePostAction" }
    requirements: { _method: get|post|delete }

bluehouseapp_audit_postcomment_delete:
    path:     /postcomment_delete
    defaults: { _controller: "bluehouseapp.controller.audit:deletePostCommentAction" }
    requirements: { _method: get|post|delete }