bluehouseapp_banedips_index:
    path:     /
    defaults: { _controller: "bluehouseapp.controller.banedips:indexAction" }

bluehouseapp_banedIPs_show:
    path:     /{id}/show
    defaults: { _controller: "bluehouseapp.controller.banedips:showAction" }

bluehouseapp_banedips_new:
    path:     /new
    defaults: { _controller: "bluehouseapp.controller.banedips:createAction" }

bluehouseapp_banedips_create:
    path:     /create
    defaults: { _controller: "bluehouseapp.controller.banedips:createAction" }
    requirements: { _method: post }

bluehouseapp_banedips_edit:
    path:     /{id}/edit
    defaults: { _controller: "bluehouseapp.controller.banedips:updateAction" }

bluehouseapp_banedips_update:
    path:     /{id}/update
    defaults: { _controller: "bluehouseapp.controller.banedips:updateAction" }
    requirements: { _method: post|put }

bluehouseapp_banedips_delete:
    path:     /{id}/delete
    defaults: { _controller: "bluehouseapp.controller.banedips:deleteAction" }
    requirements: { _method: get|post|delete }