bluehouseapp_banedIPs_index:
    path:     /
    defaults: { _controller: "bluehouseapp.controller.banedips:indexAction" }

bluehouseapp_banedIPs_show:
    path:     /{id}/show
    defaults: { _controller: "bluehouseapp.controller.banedips:showAction" }


bluehouseapp_banedIPs_create:
    path:     /create
    defaults: { _controller: "bluehouseapp.controller.banedips:createAction" }


bluehouseapp_banedIPs_update:
    path:     /{id}/update
    defaults: { _controller: "bluehouseapp.controller.banedips:updateAction" }


bluehouseapp_banedIPs_delete:
    path:     /{id}/delete
    defaults: { _controller: "bluehouseapp.controller.banedips:deleteAction" }
