members_list:
    path:     /list
    defaults: { _controller: "blackhouseapp_bluehouseapp.controller.member:listAction" }
member_enable:
    path:    /enable/{id}
    defaults: { _controller: "blackhouseapp_bluehouseapp.controller.member:enableAction" }
member_disable:
    path:     /disable/{id}
    defaults: { _controller: "blackhouseapp_bluehouseapp.controller.member:disableAction" }